---
- name: deploy_project
  become: yes
  hosts: work_group
  tasks:


    - name: clone the repo
      git:
        repo: 'git@github.com:ThakshalaMadhuwanthi/DeployPreoject.git'
        dest: /home/jenkins/DeployPreoject
        version: main
        force: yes
        accept_hostkey: yes

    - name: deploy_project
      command: docker-compose up -d --build
      args:
        chdir: /home/jenkins/DeployPreoject
      